//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CANDIDATES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANDIDATES()
        {
            this.RESULTS = new HashSet<RESULTS>();
            this.CANDIDATES_TEST = new HashSet<CANDIDATES_TEST>();
        }
    
        public int CandidateId { get; set; }

        [Required(ErrorMessage = "Please enter Full Name.")]
        [RegularExpression("^[a-zA-Z\\s]{1,50}$", ErrorMessage = "Name is invalid.")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Please select date of birth.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime Birth { get; set; }

        public string Gender { get; set; }

        [Required(ErrorMessage = "Please enter Phone.")]
        [RegularExpression("^[0][0-9]{9}$", ErrorMessage = "Phone is invalid. (0987654321 or 0123456789...)")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Please enter Email.")]
        [MaxLength(50, ErrorMessage = "Maximum 50 characters.")]
        [RegularExpression("^[\\w.]{5,32}[@][\\w.]{2,9}[.][a-zA-Z]{2,9}$", ErrorMessage = "Email is invalid.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter Address.")]
        public string Address { get; set; }

        public string Education { get; set; }

        public string WorkExperience { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTS> RESULTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANDIDATES_TEST> CANDIDATES_TEST { get; set; }
    }
}
