//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project3Entities : DbContext
    {
        public Project3Entities()
            : base("name=Project3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CANDIDATES> CANDIDATES { get; set; }
        public virtual DbSet<CANDIDATES_TEST> CANDIDATES_TEST { get; set; }
        public virtual DbSet<CORRECT_ANSWER> CORRECT_ANSWER { get; set; }
        public virtual DbSet<EXAMINATION> EXAMINATION { get; set; }
        public virtual DbSet<MANAGER> MANAGER { get; set; }
        public virtual DbSet<QUESTIONS> QUESTIONS { get; set; }
        public virtual DbSet<REL_EXAMINATION_QUESTIONS> REL_EXAMINATION_QUESTIONS { get; set; }
        public virtual DbSet<REL_MANAGER_EXAMINATION> REL_MANAGER_EXAMINATION { get; set; }
        public virtual DbSet<REL_MANAGER_ROLES> REL_MANAGER_ROLES { get; set; }
        public virtual DbSet<RESULTS> RESULTS { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<STATUS_EXAM> STATUS_EXAM { get; set; }
        public virtual DbSet<STATUS_RESULTS> STATUS_RESULTS { get; set; }
        public virtual DbSet<TOPIC> TOPIC { get; set; }
    }
}
