//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EXAMINATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAMINATION()
        {
            this.CANDIDATES_TEST = new HashSet<CANDIDATES_TEST>();
            this.REL_EXAMINATION_QUESTIONS = new HashSet<REL_EXAMINATION_QUESTIONS>();
            this.RESULTS = new HashSet<RESULTS>();
            this.REL_MANAGER_EXAMINATION = new HashSet<REL_MANAGER_EXAMINATION>();
        }
    
        public int ExaminationId { get; set; }

        [Required(ErrorMessage = "Please enter Name Examination.")]
        [MaxLength(100, ErrorMessage = "Maximum 100 characters.")]
        public string ExaminationName { get; set; }

        [Required(ErrorMessage = "Please select Start time.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}")]
        public System.DateTime Start_time { get; set; }

        [Required(ErrorMessage = "Please select End time.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}")]
        public System.DateTime End_time { get; set; }

        public int Score { get; set; }

        [Required(ErrorMessage = "Please enter Description.")]
        public string Descriptions { get; set; }

        public int StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANDIDATES_TEST> CANDIDATES_TEST { get; set; }
        public virtual STATUS_EXAM STATUS_EXAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REL_EXAMINATION_QUESTIONS> REL_EXAMINATION_QUESTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTS> RESULTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REL_MANAGER_EXAMINATION> REL_MANAGER_EXAMINATION { get; set; }
    }
}
