//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class QUESTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUESTIONS()
        {
            this.CANDIDATES_TEST = new HashSet<CANDIDATES_TEST>();
            this.REL_EXAMINATION_QUESTIONS = new HashSet<REL_EXAMINATION_QUESTIONS>();
        }
    
        public int QuestionId { get; set; }

        [Required(ErrorMessage = "Please enter Content.")]
        public string Content { get; set; }

        [Required(ErrorMessage = "Please enter Answer A.")]
        public string Answer_A { get; set; }

        [Required(ErrorMessage = "Please enter Answer B.")]
        public string Answer_B { get; set; }

        [Required(ErrorMessage = "Please enter Answer C.")]
        public string Answer_C { get; set; }

        [Required(ErrorMessage = "Please enter Answer D.")]
        public string Answer_D { get; set; }

        public int TopicId { get; set; }

        public int Point { get; set; }

        public int Correct_Answer_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANDIDATES_TEST> CANDIDATES_TEST { get; set; }
        public virtual CORRECT_ANSWER CORRECT_ANSWER { get; set; }
        public virtual TOPIC TOPIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REL_EXAMINATION_QUESTIONS> REL_EXAMINATION_QUESTIONS { get; set; }
    }
}
